# config/application.yml

SENDGRID_USERNAME: "caansonia"
SENDGRID_PASSWORD: "Lahore01"

flickr_key: "4d2cfa44828fa84913a69333cdf31149"
flickr_secret: "920b67d047dc78e6"

S3_ACCESS_KEY: "AKIAIRQOH37ZOLSGSXEA"
S3_SECRET_KEY: "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"
S3_BUCKET: "caansonia"